### ISSUE TITLE
you could try ternaries

### ISSUE THREAD

**Issue by saramic** [Johnnsonkp/learning#1]
https://github.com/Johnnsonkp/learning/blob/69e36b20ac2004de41ef889d33d6ce4287ed82ad/Exercism/javascript/lasagna/lasagna.js#L49-L56

```javascript
export function remainingMinutesInOven(actualMinutesInOven) {
  if (actualMinutesInOven < EXPECTED_MINUTES_IN_OVEN)
  {
    return EXPECTED_MINUTES_IN_OVEN - actualMinutesInOven;
  }
  else
  {
    return 0;
  }
}
```

can also be done with

```javascript
export function remainingMinutesInOven(actualMinutesInOven) {
  return actualMinutesInOven < EXPECTED_MINUTES_IN_OVEN ?
    EXPECTED_MINUTES_IN_OVEN - actualMinutesInOven :
    0;
}
```

although you don't want to over use ternaries either.

more info https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_operator

**Comment by Johnnsonkp** [comment]
Thanks for suggesting an alternative solution using ternaries!  It does simplify the code, but yes you're right I can see how overusing them can become really messy.
